version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:12345
    volumes:
      - .:/app
    ports:
      - "12345:12345"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: roma_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
