# Generated by Django 4.2 on 2025-07-05 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(blank=True, max_length=100, verbose_name='단과대학')),
                ('major', models.CharField(blank=True, max_length=100, verbose_name='전공')),
                ('student_id', models.CharField(blank=True, max_length=20, verbose_name='학번')),
                ('current_lifestyle', models.TextField(blank=True, verbose_name='현재 생활패턴')),
                ('desired_lifestyle', models.TextField(blank=True, verbose_name='원하는 생활패턴')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
