# Generated by Django 4.2 on 2025-07-07 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='이름')),
                ('gender', models.CharField(blank=True, choices=[('M', '남'), ('F', '여')], max_length=1, null=True, verbose_name='성별')),
                ('birth_year', models.CharField(blank=True, max_length=4, null=True, verbose_name='생년')),
                ('college', models.CharField(blank=True, max_length=100, null=True, verbose_name='단과대학')),
                ('major', models.CharField(blank=True, max_length=100, null=True, verbose_name='전공')),
                ('mbti', models.CharField(blank=True, max_length=4, null=True, verbose_name='MBTI')),
                ('bedtime', models.CharField(blank=True, choices=[('E', '8-10시'), ('M', '11-12시'), ('L', '자정-1시'), ('VL', '2시~')], max_length=2, null=True, verbose_name='취침시간')),
                ('wakeup_time', models.CharField(blank=True, choices=[('E', '~6시'), ('M', '7-8시'), ('L', '9-10시'), ('VL', '11시~')], max_length=2, null=True, verbose_name='기상시간')),
                ('sleeping_habit', models.CharField(blank=True, choices=[('N', '없음'), ('C', '이갈이'), ('S', '코골이')], max_length=1, null=True, verbose_name='잠버릇')),
                ('noise_sensitivity', models.CharField(blank=True, max_length=100, null=True, verbose_name='잠귀(밝기)')),
                ('shower_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='샤워시간')),
                ('room_dryer', models.CharField(blank=True, choices=[('Y', 'O'), ('N', 'X')], max_length=1, null=True, verbose_name='방에서 드라이기')),
                ('in_room_call', models.CharField(blank=True, choices=[('N', '상관X'), ('O', '밖에서만')], max_length=1, null=True, verbose_name='실내통화')),
                ('heat_sensitivity', models.CharField(blank=True, choices=[('L', '적게 탐'), ('M', '중간'), ('H', '많이 탐')], max_length=1, null=True, verbose_name='더위')),
                ('cold_sensitivity', models.CharField(blank=True, choices=[('L', '적게 탐'), ('M', '중간'), ('H', '많이 탐')], max_length=1, null=True, verbose_name='추위')),
                ('perfume_usage', models.CharField(blank=True, max_length=20, null=True, verbose_name='향수')),
                ('smoking', models.CharField(blank=True, choices=[('N', '비흡연'), ('Y', '흡연')], max_length=1, null=True, verbose_name='흡연여부')),
                ('bug_response', models.CharField(blank=True, choices=[('C', '못잡음'), ('M', '중간'), ('P', '잘잡음')], max_length=1, null=True, verbose_name='벌레')),
                ('late_night_snack', models.CharField(blank=True, choices=[('O', '자주'), ('S', '가끔'), ('N', '안먹음')], max_length=1, null=True, verbose_name='야식')),
                ('cleaning_style', models.CharField(blank=True, choices=[('O', '한번에'), ('M', '중간'), ('L', '더러울때')], max_length=1, null=True, verbose_name='청소')),
                ('pref_same_college', models.CharField(blank=True, choices=[('Y', '선호'), ('N', '비선호'), ('D', '상관없음')], max_length=1, null=True, verbose_name='선호 단과대')),
                ('pref_bedtime', models.CharField(blank=True, choices=[('E', '8-10시'), ('M', '11-12시'), ('L', '자정-1시'), ('VL', '2시~')], max_length=2, null=True, verbose_name='선호 취침시간')),
                ('pref_wakeup_time', models.CharField(blank=True, choices=[('E', '~6시'), ('M', '7-8시'), ('L', '9-10시'), ('VL', '11시~')], max_length=2, null=True, verbose_name='선호 기상시간')),
                ('pref_sleeping_habit', models.CharField(blank=True, choices=[('Y', '있어도 됨'), ('N', '없어야 함'), ('D', '상관없음')], max_length=1, null=True, verbose_name='선호 잠버릇')),
                ('pref_in_room_call', models.CharField(blank=True, choices=[('N', '상관X'), ('O', '밖에서만')], max_length=1, null=True, verbose_name='선호 실내통화')),
                ('pref_room_dryer', models.CharField(blank=True, choices=[('Y', 'O'), ('N', 'X')], max_length=1, null=True, verbose_name='선호 방에서 드라이기')),
                ('pref_heat_sensitivity', models.CharField(blank=True, choices=[('L', '적게 탐'), ('M', '중간'), ('H', '많이 탐')], max_length=1, null=True, verbose_name='선호 더위')),
                ('pref_cold_sensitivity', models.CharField(blank=True, choices=[('L', '적게 탐'), ('M', '중간'), ('H', '많이 탐')], max_length=1, null=True, verbose_name='선호 추위')),
                ('pref_smoking', models.CharField(blank=True, choices=[('Y', '흡연자'), ('N', '비흡연자'), ('D', '상관없음')], max_length=1, null=True, verbose_name='선호 흡연여부')),
                ('pref_bug_response', models.CharField(blank=True, choices=[('C', '못잡음'), ('M', '중간'), ('P', '잘잡음')], max_length=1, null=True, verbose_name='선호 벌레')),
                ('pref_late_night_snack', models.CharField(blank=True, choices=[('O', '자주'), ('S', '가끔'), ('N', '안먹음')], max_length=1, null=True, verbose_name='선호 야식')),
                ('pref_cleaning_style', models.CharField(blank=True, choices=[('O', '한번에'), ('M', '중간'), ('L', '더러울때')], max_length=1, null=True, verbose_name='선호 청소')),
                ('pref_relationship', models.CharField(blank=True, choices=[('F', '짱친'), ('M', '중간'), ('B', '비즈니스'), ('D', '상관없음')], max_length=1, null=True, verbose_name='원하는 룸메 관계')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
